#!/usr/bin/env bash
# Author: Rafael Cavalcanti <https://rafaelc.org/dev>

set -euo pipefail

notify-send -i "tomato" "Pomodoro" "Pomodoro started."
systemd-run  \
  --user \
  --collect \
  --unit "pomodoro-check-for-done" \
  "$HOME/.pomodoro/check-for-done/check-for-done"
