#!/usr/bin/env bash
#
# Dotfiles installation script.
#
# Copyright (C) 2020 Rafael Cavalcanti - rafaelc.org
# Licensed under GPLv3

set -euo pipefail

readonly script_name=$(basename "${0}")
readonly script_dir="$(dirname "$(readlink -f "$0")")"

main() {
  # Initialize submodules.
  git submodule update --init --recursive

  rm_conflicts
  make_dirs

  pick_install
  if $gui; then
    do_stow cli gui
    load_dconf
  else
    do_stow cli
  fi

  do_stow_host
}

log() {
  printf "%s\n" "$*" 1>&2
}

# args: command_to_check ...
check_cmd() {
  for cmd in "$@"; do
    if ! command -v $cmd >/dev/null; then
      printf "Install %s before running this script.\n" "$cmd"
      exit 1
    fi
  done
}

pick_install() {
  select option in "Only CLI" "CLI+GUI"; do
    case $option in
    "CLI+GUI")
      gui=true
      break
      ;;
    "Only CLI")
      gui=false
      break
      ;;
    *)
      printf "Invalid option.\n"
      ;;
    esac
  done
}

make_dirs() {
  # Create directories we don't want Stow to own.
  mkdir -p "$HOME/.config"
  mkdir -p "$HOME/.local/share"
  mkdir -p "$HOME/.vim"

  # Create other directories I use.
  mkdir -p "$HOME/.local/bin"
  mkdir -p "$HOME/.local/opt"
}

# Remove conflicting skel files.
rm_conflicts() {
  local conflicts=(".bash_logout" ".bashrc" ".profile")

  for file in "$conflicts"; do
    if [[ -f "$script_dir/cli/$file" && -f "~/$file" ]]; then
      rm -v "~/$file"
    fi
  done
}

load_dconf() {
  check_cmd dconf

  log "Loading dconf settings..."
  cat dconf/*.conf | dconf load /
}

do_stow() {
  check_cmd stow

  log "Doing stow for $*..."
  stow -t ~ "$@"
}

do_stow_host() {
  case "$(hostname)" in
    localhost) local host="termux" ;;
    *) local host="$(hostname)" ;;
  esac

  [[ -d "hosts/${host}" ]] || return

  log "Found host specific files."
  cd hosts
  do_stow "${host}"
}

main "$@"
