#!/usr/bin/env bash
# Dotfiles installation script
# Author: Rafael Cavalcanti

if ! command -v stow >/dev/null; then
  printf "Install stow before running this script.\n"
  exit 1
fi

# Initialize submodules
git submodule update --init --recursive

if [[ "$HOSTNAME" == "localhost" ]]; then
  host="termux"
else
  host="$(hostname)"
fi

select option in "Only CLI" "CLI+GUI"; do
  case $option in
  "CLI+GUI")
    printf "Installing CLI and GUI configs...\n"
    stow -t ~ cli gui
    break
    ;;
  "Only CLI")
    printf "Installing only CLI...\n"
    stow -t ~ cli
    break
    ;;
  *)
    printf "Invalid option.\n"
    ;;
  esac
done

if [[ -f "hosts/${host}" ]]; then
  printf "Host is %s. Installing host specific configs...\n" "${host}"

  cd hosts
  stow -t ~ "${host}"
fi
