#!/usr/bin/env bash
#
# Bootstrapping script for yadm.
#
# Copyright (C) 2020 Rafael Cavalcanti - rafaelc.org
# Licensed under GPLv3

set -euo pipefail

readonly script_name=$(basename "${0}")
readonly script_dir="$(dirname "$(readlink -f "$0")")"

main() {
  log "Initializing submodules..."
  yadm submodule update --init --recursive

  log "Creating directories..."
  mkdir -p "$HOME/.local/opt"
}

log() {
  printf "%s\n" "$*" 1>&2
}

main "$@"
