#!/usr/bin/env bash
#
# Bootstrapping script for yadm.
#
# Copyright (C) 2020 Rafael Cavalcanti <https://rafaelc.org/dev>
# Licensed under GPLv3

set -euo pipefail

main() {
  # To hide README and LICENSE
  log "Setting sparse checkout..."
  yadm gitconfig core.sparseCheckout true
  yadm sparse-checkout set '/*' '!/README.md' '!/LICENSE'

  # Necessary if submodule remote url changes
  log "Syncing submodules if already present..."
  yadm submodule sync

  log "Initializing submodules..."
  yadm submodule update --init --recursive

  log "Adding repository config..."
  yadm gitconfig include.path ~/.config/yadm/gitconfig
  yadm gitconfig core.hooksPath ~/.config/yadm/hooks-git

  log "Installing neovim plugins..."
  nvim +PlugInstall +qa!
}

log() {
  printf "%s\n" "$*" 1>&2
}

main "$@"
