#!/usr/bin/env bash
#
# Install latest yadm from the repo.
# This is intended to systems stuck with older versions of yadm.
#
# Copyright (C) 2020 Rafael Cavalcanti - rafaelc.org
# Licensed under GPLv3

set -euo pipefail

printf "Cloning repo to /opt/yadm...\n"
sudo git clone --depth=1 https://github.com/TheLocehiliosan/yadm.git /opt/yadm

printf "Linking to /usr/local/bin...\n"
sudo ln -s /opt/yadm/yadm /usr/local/bin
