#!/bin/sh
# Author: Rafael Cavalcanti
# Git hook to run a command after `git merge` / `git pull` if a specified file was changed.

# Fix weird terminal behaviour
exec </dev/tty >/dev/tty

readonly changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

has_changed() {
  echo "$changed_files" | grep --quiet -E "$1"
}

# Update VIM plugins
if has_changed .vimrc; then
  echo "\n[Hook] vimrc changed: Installing/cleaning VIM plugins..."
  # PlugInstall doesn't proceed with GIT_DIR set (https://github.com/junegunn/vim-plug/issues/506).
  (unset GIT_DIR GIT_WORK_TREE && vim +PlugClean! PlugInstall +qa!)
fi

if has_changed yadm/bootstrap; then
  echo "\n[Hook] yadm's bootstrap changed: Running it again..."
  yadm bootstrap
fi

if has_changed .gitmodules; then
  echo "\n[Hook] ~/.gitmodules changed: Syncing and initializing submodules..."
  yadm submodule sync --recursive
  yadm submodule update --init --recursive
fi

