#!/bin/sh
# Author: Rafael Cavalcanti
# Git hook to run a command after `git merge` / `git pull` if a specified file was changed.

# Fix weird terminal behaviour (only if attatched to terminal)
if [ -t 1 ]; then
  exec </dev/tty >/dev/tty
fi

readonly changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

has_changed() {
  echo "$changed_files" | grep --quiet -E "$1"
}

# Update VIM plugins
if has_changed init.vim; then
  echo "\n[Hook] vimrc changed: Installing/cleaning neovim plugins..."
  # PlugInstall doesn't proceed with GIT_DIR set (https://github.com/junegunn/vim-plug/issues/506).
  (unset GIT_DIR GIT_WORK_TREE && nvim +PlugClean! PlugInstall +qa!)
fi

if has_changed dotfiles/install; then
  echo "\n[Hook] dotfiles install script changed: Running it again..."
  git install
fi

if has_changed .gitmodules; then
  echo "\n[Hook] ~/.gitmodules changed: Syncing and initializing submodules..."
  git submodule sync --recursive
  git submodule update --init --recursive
fi

if has_changed .config/jumps.conf; then
  echo "\n[Hook] jumps.conf changed: Re-generating jumps..."
  gen-jumps
fi
