#!/bin/sh
# Author: Rafael Cavalcanti
# Git hook to run a command after `git merge` / `git pull` if a specified file was changed.

# Fix weird terminal behaviour (only if attatched to terminal)
if [ -t 1 ]; then
  exec </dev/tty >/dev/tty
fi

readonly changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

has_changed() {
  echo "$changed_files" | grep --quiet -E "$1"
}

if has_changed dotfiles/install; then
  printf "\n[Hook] dotfiles install script changed: Running it again...\n"
  git install
fi

if has_changed .gitmodules; then
  printf "\n[Hook] ~/.gitmodules changed: Syncing and initializing submodules...\n"
  git submodule sync --recursive
  git submodule update --init --recursive
fi

if has_changed .config/jumps.conf; then
  printf "\n[Hook] jumps.conf changed: Re-generating jumps...\n"
  gen-jumps
fi
