#!/data/data/com.termux/files/usr/bin/bash

. ~/.zprofile

bash ~/.local/bin/notes name-x

# Workaround on AOSP.
# Without this, if the markdown app is locked, and Termux is not open,
# the authentication pop-up shows up only for a brief moment and
# nothing more happens.
sleep 15s
