#!/data/data/com.termux/files/usr/bin/env bash
# Copyright (C) 2020 Rafael Cavalcanti - rafaelc.org
# Licensed under GPLv3

# We need PATH, MPD_HOST
source ~/.zprofile

main() {
  select_action "$@"
}

select_action() {
  printf "What should I do?\n" >&2

  select option in "Download video" "Download audio" "MPD: Play now" "MPD: Queue"; do
    case $option in
      "Download video")
        cd /sdcard/Download || cd
        youtube-dl "$@" || notify_error "$@"
        break
        ;;
      "Download audio")
        cd /sdcard/Download || cd
        youtube-dl --extract-audio "$@" || notify_error "$@"
        break
        ;;
      "MPD: Play now")
        bash myt --play-now "$@" || notify_error "$@"
        break
        ;;
      "MPD: Queue")
        bash myt --queue "$@" || notify_error "$@"
        break
        ;;
      *)
        printf "Invalid option.\n" 1>&2 ;;
    esac
  done
}

notify_error() {
  termux-notification \
    -t "Error (tap to open URL)" \
    -c "$option - URL: $*" \
    --action "termux-open-url $*"
}

main "$@"
