#!/data/data/com.termux/files/usr/bin/env bash
# Copyright (C) 2020 Rafael Cavalcanti - rafaelc.org
# Licensed under GPLv3

# We need PATH, MPD_HOST
source ~/.zprofile

main() {
  select_action "$@"
}

select_action() {
  printf "What should I do?\n" >&2

  select option in "Download video" "Download audio" "MPD: Play now" "MPD: Queue"; do
    case $option in
      "Download video")
        cd /sdcard/Download || cd
        youtube-dl "$@" || hold
        break
        ;;
      "Download audio")
        cd /sdcard/Download || cd
        youtube-dl --extract-audio "$@" || hold
        break
        ;;
      "MPD: Play now")
        bash myt --play-now "$@" || hold
        break
        ;;
      "MPD: Queue")
        bash myt --queue "$@" || hold
        break
        ;;
      *)
        printf "Invalid option.\n" 1>&2 ;;
    esac
  done
}

hold() {
  printf "\nPress any key to exit."
  read
}

main "$@"
