#!/bin/bash
#
# Copyright (C) 2024 Rafael Cavalcanti <https://rafaelc.org/dev>
# Licensed under GPLv3

readonly git_dir="$HOME/obsidian-main-git"
readonly work_tree="$HOME/storage/shared/Documents/obsidian-main"
readonly repo_url="ssh://git@192.168.1.201:222/rafael/obsidian-main"


# Place git in Termux's internal storage as workaround to
# <https://github.com/termux/termux-app/issues/3385>.
git_cmd() {
  git --git-dir "$git_dir" --work-tree "$work_tree" "$@"
}

log() {
  local -r upper_text="${*^^}"
  echo
  echo -e "\033[1m${upper_text}\033[0m"
}

get_device_name() {
  # Hostname available
  local -r hostname="$(hostname)"
  if [[ -n "$hostname" ]] && [[ "$hostname" != "localhost" ]]; then
    echo $hostname
    return
  fi

  # Can't get Android device and no hostname available
  if ! command -v getprop > /dev/null; then
    echo "Unknown host"
    return
  fi

  # Android device, fallback to Termux
  local -r android_device="$(getprop ro.product.brand) $(getprop ro.product.device)"
  echo ${android_device:-Termux}
}

cat << "EOF"
       _         _     _ _
  ___ | |__  ___(_) __| (_) __ _ _ __
 / _ \| '_ \/ __| |/ _` | |/ _` | '_ \
| (_) | |_) \__ \ | (_| | | (_| | | | |
 \___/|_.__/|___/_|\__,_|_|\__,_|_| |_|


 _ __ ___ _ __   ___
| '__/ _ \ '_ \ / _ \
| | |  __/ |_) | (_) |
|_|  \___| .__/ \___/
         |_|

This will sync your obsidian local repo (pull, commit and push).
Designed to be used on mobile devices, but should work on any device.

EOF


if [[ ! -d "$git_dir" || ! -d "$work_tree" ]] then
  printf "Repo not found. Cloning...\n"

  # Might make it faster
  termux-wake-lock

  mkdir "$git_dir"
  git_cmd clone "$repo_url"
  echo "gitdir: $git_dir" > "$work_tree/.git"

  termux-wake-unlock
fi

cd "$repo_dir"


log "Pulling..."
git_cmd pull

log "Commiting and pushing..."
git_cmd add .
git_cmd commit --stat --edit --verbose --message="Update on $(get_device_name): $(date '+%Y-%m-%d %H:%M:%S')"
git_cmd push
