#!/bin/bash
#
# Copyright (C) 2024 Rafael Cavalcanti <https://rafaelc.org/dev>
# Licensed under GPLv3

log() {
  local -r upper_text="${*^^}"
  echo -e "\033[1m${upper_text}\033[0m"
}

get_device_name() {
  # Hostname available
  local -r hostname="$(hostname)"
  if [[ -n "$hostname" ]] && [[ "$hostname" != "localhost" ]]; then
    echo $hostname
    return
  fi

  # Can't get Android device and no hostname available
  if ! command -v getprop > /dev/null; then
    echo "Unknown host"
    return
  fi

  # Android device, fallback to Termux
  local -r android_device="$(getprop ro.product.brand) $(getprop ro.product.device)"
  echo ${android_device:-Termux}
}

cat << "EOF"
       _         _     _ _
  ___ | |__  ___(_) __| (_) __ _ _ __
 / _ \| '_ \/ __| |/ _` | |/ _` | '_ \
| (_) | |_) \__ \ | (_| | | (_| | | | |
 \___/|_.__/|___/_|\__,_|_|\__,_|_| |_|


 _ __ ___ _ __   ___
| '__/ _ \ '_ \ / _ \
| | |  __/ |_) | (_) |
|_|  \___| .__/ \___/
         |_|

This will sync your obsidian local repo (pull, commit and push).

EOF

readonly repo_dir="$HOME/Documents/obsidian-main"

if [[ ! -d "$repo_dir" ]]; then
  printf "Repo not found. Exiting.\n"
  exit
fi

cd "$repo_dir"


log "Pulling..."
git pull

log "Commiting and pushing..."
git add .
git commit --stat --message="Update on $(get_device_name): $(date '+%Y-%m-%d %H:%M:%S')"
git push
