#!/usr/bin/env bash
#
# Check if pomodoro is done, notify and finish it.
# Author: Rafael Cavalcanti <https://rafaelc.org/dev>

set -euo pipefail

readonly done_tune="$HOME/.pomodoro/check-for-done/done.ogg"

while true; do
  status="$(pomodoro status --format "%r")"

  case "$status" in
    "0:00")
      pomodoro finish
      mpv --no-config "$done_tune"
      exit
      ;;
    "")
      exit
  esac

  sleep 1s
done
